image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start web server
    command: gp await-port 23000 && gp preview https://training.seqera.io    

  - name: Download Nextflow Tutorial
    init: |
      echo 'init script' # runs during prebuild
      echo 'start script'
      
    command: |
      curl -s https://get.nextflow.io | bash
      chmod +x nextflow
      sudo mv nextflow /usr/local/bin/
      docker pull nextflow/rnaseq-nf
      sudo apt install  -y tree
      sudo apt install  -y graphviz
      unset JAVA_TOOL_OPTIONS
      alias conda_activate=". /opt/conda/etc/profile.d/conda.sh; conda activate base"
      cd nf-training
      
vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore                 # Language support for .gitignore files
    # - cssho.vscode-svgviewer                 # SVG viewer
    - davidanson.vscode-markdownlint         # Markdown/CommonMark linting and style checking for Visual Studio Code
    # - eamodio.gitlens                        # Quickly glimpse into whom, why, and when a line or code block was changed
    # - EditorConfig.EditorConfig              # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree                  # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv                # Highlight columns in csv files in different colors
    # - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow                 # Highlight indentation level
    - streetsidesoftware.code-spell-checker  # Spelling checker for source code
    - anwar.papyrus-pdf                      # PDF preview
